# Generated by Django 5.0.6 on 2024-06-15 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transacao",
            name="modulo",
        ),
        migrations.DeleteModel(
            name="Modulo",
        ),
        migrations.DeleteModel(
            name="Transacao",
        ),
    ]
