# Generated by Django 5.0.6 on 2024-06-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "grupos",
                    models.ManyToManyField(related_name="modulos", to="auth.group"),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, related_name="modulos", to="auth.permission"
                    ),
                ),
            ],
            options={
                "db_table": "modulo",
            },
        ),
        migrations.CreateModel(
            name="Transacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "grupos",
                    models.ManyToManyField(
                        blank=True, related_name="transacoes", to="auth.group"
                    ),
                ),
                (
                    "modulos",
                    models.ManyToManyField(
                        related_name="transacoes", to="galeria.modulo"
                    ),
                ),
                (
                    "permissoes",
                    models.ManyToManyField(
                        blank=True, related_name="transacoes", to="auth.permission"
                    ),
                ),
            ],
            options={
                "db_table": "transacao",
            },
        ),
        migrations.CreateModel(
            name="UrlPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=255, unique=True)),
                ("permissions", models.ManyToManyField(to="auth.permission")),
            ],
        ),
    ]
