# Generated by Django 5.0.6 on 2024-06-08 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_alter_transacao_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='modulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='galeria.modulo'),
        ),
    ]
