# Generated by Django 5.0.6 on 2024-06-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_alter_transacao_modulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='modulo',
        ),
        migrations.AddField(
            model_name='transacao',
            name='modulos',
            field=models.ManyToManyField(related_name='transacoes', to='galeria.modulo'),
        ),
    ]
