# Generated by Django 5.0.6 on 2024-06-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('galeria', '0004_remove_transacao_modulo_transacao_modulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='permissoes',
            field=models.ManyToManyField(blank=True, related_name='transacoes', to='auth.permission'),
        ),
    ]
