# Generated by Django 5.0.6 on 2024-06-10 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
