# Generated by Django 5.0.6 on 2024-06-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("galeria", "0009_modulo_grupos_delete_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="transacao",
            name="grupos",
            field=models.ManyToManyField(
                blank=True, related_name="transacoes", to="auth.group"
            ),
        ),
    ]
